/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Erisson
 */
public class TelaInicialGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialGerente
     */
    public TelaInicialGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        bConMateria = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        bConAluno = new javax.swing.JButton();
        bConGerente = new javax.swing.JButton();
        bConProfessor = new javax.swing.JButton();
        bConMat = new javax.swing.JButton();
        bConTurma = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bAlterarSenha = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastrar = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        jSobre = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bConMateria.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book.png"))); // NOI18N
        bConMateria.setText("Matérias");
        bConMateria.setToolTipText("");
        bConMateria.setFocusable(false);
        bConMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConMateria.setMaximumSize(new java.awt.Dimension(75, 45));
        bConMateria.setMinimumSize(new java.awt.Dimension(75, 45));
        bConMateria.setPreferredSize(new java.awt.Dimension(75, 45));
        bConMateria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConMateriaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADA - Tela Inicial Gerente");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bConAluno.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_male_user.png"))); // NOI18N
        bConAluno.setText("Alunos");
        bConAluno.setToolTipText("");
        bConAluno.setFocusable(false);
        bConAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConAluno.setMaximumSize(new java.awt.Dimension(75, 45));
        bConAluno.setMinimumSize(new java.awt.Dimension(75, 45));
        bConAluno.setPreferredSize(new java.awt.Dimension(75, 45));
        bConAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConAlunoActionPerformed(evt);
            }
        });
        jToolBar1.add(bConAluno);

        bConGerente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_user.png"))); // NOI18N
        bConGerente.setText("Gerentes");
        bConGerente.setToolTipText("");
        bConGerente.setFocusable(false);
        bConGerente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConGerente.setMaximumSize(new java.awt.Dimension(75, 45));
        bConGerente.setMinimumSize(new java.awt.Dimension(75, 45));
        bConGerente.setPreferredSize(new java.awt.Dimension(75, 45));
        bConGerente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConGerenteActionPerformed(evt);
            }
        });
        jToolBar1.add(bConGerente);

        bConProfessor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_business_user.png"))); // NOI18N
        bConProfessor.setText("Professores");
        bConProfessor.setToolTipText("");
        bConProfessor.setFocusable(false);
        bConProfessor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConProfessor.setMaximumSize(new java.awt.Dimension(75, 45));
        bConProfessor.setMinimumSize(new java.awt.Dimension(75, 45));
        bConProfessor.setPreferredSize(new java.awt.Dimension(75, 45));
        bConProfessor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConProfessorActionPerformed(evt);
            }
        });
        jToolBar1.add(bConProfessor);

        bConMat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/materias.png"))); // NOI18N
        bConMat.setText("Matérias");
        bConMat.setToolTipText("");
        bConMat.setFocusable(false);
        bConMat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConMat.setMaximumSize(new java.awt.Dimension(75, 45));
        bConMat.setMinimumSize(new java.awt.Dimension(75, 45));
        bConMat.setPreferredSize(new java.awt.Dimension(75, 45));
        bConMat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConMatActionPerformed(evt);
            }
        });
        jToolBar1.add(bConMat);

        bConTurma.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bConTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/chalk_board.png"))); // NOI18N
        bConTurma.setText("Turmas");
        bConTurma.setToolTipText("");
        bConTurma.setFocusable(false);
        bConTurma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConTurma.setMaximumSize(new java.awt.Dimension(75, 45));
        bConTurma.setMinimumSize(new java.awt.Dimension(75, 45));
        bConTurma.setPreferredSize(new java.awt.Dimension(75, 45));
        bConTurma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConTurmaActionPerformed(evt);
            }
        });
        jToolBar1.add(bConTurma);
        jToolBar1.add(jSeparator4);

        bAlterarSenha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/key.png"))); // NOI18N
        bAlterarSenha.setText("Alterar Senha");
        bAlterarSenha.setToolTipText("");
        bAlterarSenha.setFocusable(false);
        bAlterarSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlterarSenha.setMaximumSize(new java.awt.Dimension(75, 45));
        bAlterarSenha.setMinimumSize(new java.awt.Dimension(75, 45));
        bAlterarSenha.setPreferredSize(new java.awt.Dimension(75, 45));
        bAlterarSenha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarSenhaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlterarSenha);
        jToolBar1.add(jSeparator2);

        bSair.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        bSair.setText("Sair");
        bSair.setToolTipText("");
        bSair.setFocusable(false);
        bSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSair.setMaximumSize(new java.awt.Dimension(75, 45));
        bSair.setMinimumSize(new java.awt.Dimension(75, 45));
        bSair.setPreferredSize(new java.awt.Dimension(75, 45));
        bSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        jToolBar1.add(bSair);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo ajuda.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        mCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        mCadastrar.setText("Cadastrar");
        mCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastrarActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Aluno");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mCadastrar.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Gerente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mCadastrar.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Professor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mCadastrar.add(jMenuItem2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Matéria");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mCadastrar.add(jMenuItem6);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Turma");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mCadastrar.add(jMenuItem4);

        jMenuBar1.add(mCadastrar);

        jAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jAjuda.setText("Ajuda");
        jAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jAjuda);

        jSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/info.png"))); // NOI18N
        jSobre.setText("Sobre");
        jSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSobreMouseClicked(evt);
            }
        });
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });
        jMenuBar1.add(jSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(671, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastrarActionPerformed
       
    }//GEN-LAST:event_mCadastrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       TelaCadastroGerente obj = new TelaCadastroGerente();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       TelaCadastroDocente obj = new TelaCadastroDocente();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       TelaCadastroDiscente obj = new TelaCadastroDiscente();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      
        TelaCadastroTurma obj = new TelaCadastroTurma();
        obj.setVisible(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       TelaCadastroMateria obj = new TelaCadastroMateria();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void bConGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConGerenteActionPerformed
      TelaListaGerente obj = new TelaListaGerente();
        obj.setVisible(true); 
    }//GEN-LAST:event_bConGerenteActionPerformed

    private void bAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarSenhaActionPerformed
        TelaAlterarSenha obj = new TelaAlterarSenha();
        obj.setVisible(true);
    }//GEN-LAST:event_bAlterarSenhaActionPerformed

    private void bConAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConAlunoActionPerformed
        TelaListaDiscente obj = new TelaListaDiscente();
        obj.setVisible(true);
    }//GEN-LAST:event_bConAlunoActionPerformed

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSobreActionPerformed
        
    }//GEN-LAST:event_jSobreActionPerformed

    private void bConProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConProfessorActionPerformed
        TelaListaDocente obj = new TelaListaDocente();
        obj.setVisible(true);
    }//GEN-LAST:event_bConProfessorActionPerformed

    private void bConMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConMateriaActionPerformed
        
    }//GEN-LAST:event_bConMateriaActionPerformed

    private void bConTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConTurmaActionPerformed
        TelaListaTurma obj = new TelaListaTurma();
        obj.setVisible(true);
    }//GEN-LAST:event_bConTurmaActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
         
        System.out.println(TelaLogin.sAtual);
        System.out.print(TelaLogin.lAtual);
        
        this.dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void jSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSobreMouseClicked
        // TODO add your handling code here:
        TelaSobre obj = new TelaSobre();
        obj.setVisible(true);
    }//GEN-LAST:event_jSobreMouseClicked

    private void jAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAjudaMouseClicked
        TelaAjuda obj = new TelaAjuda();
        obj.setVisible(true);
    }//GEN-LAST:event_jAjudaMouseClicked

    private void bConMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConMatActionPerformed
        TelaListaMateria obj = new TelaListaMateria();
        obj.setVisible(true);
    }//GEN-LAST:event_bConMatActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarSenha;
    private javax.swing.JButton bConAluno;
    private javax.swing.JButton bConGerente;
    private javax.swing.JButton bConMat;
    private javax.swing.JButton bConMateria;
    private javax.swing.JButton bConProfessor;
    private javax.swing.JButton bConTurma;
    private javax.swing.JButton bSair;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JMenu jSobre;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mCadastrar;
    // End of variables declaration//GEN-END:variables
}
